name: news_brief
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.1
  go_router: ^14.3.0
  talker: ^4.4.1
  talker_flutter: ^4.4.1
  path_provider: ^2.0.0 
  dio: ^5.7.0
  quotable: ^0.0.1
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  talker_dio_logger: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 
  
